INSERT INTO sample (id, username, algo, result) VALUES (1, 'maxi2', 2, 2.24);
INSERT INTO sample (id, username, algo, result) VALUES (2, 'maksym', 1, 7.8863495173726745);
INSERT INTO sample (id, username, algo, result) VALUES (3, 'ur mommy', 1, 21.9);
INSERT INTO sample (id, username, algo, result) VALUES (4, 'nice guy', 1, 22.13);
INSERT INTO sample (id, username, algo, result) VALUES (5, '3eee', 3, 0);
INSERT INTO sample (id, username, algo, result) VALUES (6, 'sample user', 1, 7.812559200041264);
INSERT INTO sample (id, username, algo, result) VALUES (7, 'sample user', 2, 14.35);
INSERT INTO sample (id, username, algo, result) VALUES (8, 'maksym tymoshyk', 3, 12.87);
INSERT INTO sample (id, username, algo, result) VALUES (9, 'hehe', 3, 0);
INSERT INTO sample (id, username, algo, result) VALUES (10, 'hehe', 3, 12.87);
INSERT INTO sample (id, username, algo, result) VALUES (11, 'hehe', 3, 4.83);
INSERT INTO sample (id, username, algo, result) VALUES (12, 'hehe', 3, 2);
INSERT INTO sample (id, username, algo, result) VALUES (13, 'hehe', 2, 12.87);
INSERT INTO sample (id, username, algo, result) VALUES (14, 'hehe', 2, 37.06);
INSERT INTO sample (id, username, algo, result) VALUES (15, 'hehe', 1, 4.83);
INSERT INTO sample (id, username, algo, result) VALUES (16, 'hehe', 3, 7.81);
INSERT INTO sample (id, username, algo, result) VALUES (17, 'hehe', 1, 7.81);